### Importing libraries

In [134]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans
from sklearn import svm

# The real project

we have list of recepies of making cupcake and muffincake with diffrent features like (flour,milk,suger,egg,baking powder,vanilla and salt ) we want to know if we have new recepies so its cupcake or muffincake?

In [135]:
import pandas as pd
data=pd.read_csv('svm-muffin-cupcake.csv')

data

       type  flour  milk  suger  butter  egg  baking powder  vanilla  salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  cupcake     39     0     26      19   14              1        1     0
11  cupcake     42    21     16      10    8              3        0     0
12  cupcake     34    17     20      20    5              2        1     0
13  cupcake     39    13     17      19   10              1        1     0
14  cupcake     38    15     23      15    8              0        1     0
15  cupcake     42    18     25       9    5              1        0     0
16  cupcake     36    14     21      14   11              2        1     0
17  cupcake     38    15     31       8    6              1        1     0
18  cupcake     36    16     24      12    9              1        1     0
19  cupcake     34    17     23      11   13              0        1     0

in this example as you can see there is labels that is muffin and cupcake and also features that are flour,milk,suger,egg,baking powder,vanilla and salt so in this example as we have the labels means this example is supervised so no need to do kmeans as unsupervised classifier to find the labels. so we can put muffin as label 0 and cupcake as label 1 so its integer model and its not numeriek. so with this method we can change the type of data to 0 and 1.

In [136]:
dic={'Muffin':0,'cupcake':1}
data['type']=data['type'].map(dic)

In [137]:
data

    type  flour  milk  suger  butter  egg  baking powder  vanilla  salt
0      0     55    28      3       7    5              2        0     0
1      0     47    24     12       6    9              1        0     0
2      0     47    23     18       6    4              1        0     0
3      0     45    11     17      17    8              1        0     0
4      0     50    25     12       6    5              2        1     0
5      0     55    27      3       7    5              2        1     0
6      0     54    27      7       5    5              2        0     0
7      0     47    26     10      10    4              1        0     0
8      0     50    17     17       8    6              1        0     0
9      0     50    17     17      11    4              1        0     0
10     1     39     0     26      19   14              1        1     0
11     1     42    21     16      10    8              3        0     0
12     1     34    17     20      20    5              2        1     0
13     1     39    13     17      19   10              1        1     0
14     1     38    15     23      15    8              0        1     0
15     1     42    18     25       9    5              1        0     0
16     1     36    14     21      14   11              2        1     0
17     1     38    15     31       8    6              1        1     0
18     1     36    16     24      12    9              1        1     0
19     1     34    17     23      11   13              0        1     0

now we want to put all features(from firth column to the last one) as x and column 0(type) that is label as a y. so with this method can choose x and y as features and labels.

In [144]:
x=data.values[:,1:]
y=data.values[:,0]

In [145]:
x

array([[55, 28,  3,  7,  5,  2,  0,  0],
       [47, 24, 12,  6,  9,  1,  0,  0],
       [47, 23, 18,  6,  4,  1,  0,  0],
       [45, 11, 17, 17,  8,  1,  0,  0],
       [50, 25, 12,  6,  5,  2,  1,  0],
       [55, 27,  3,  7,  5,  2,  1,  0],
       [54, 27,  7,  5,  5,  2,  0,  0],
       [47, 26, 10, 10,  4,  1,  0,  0],
       [50, 17, 17,  8,  6,  1,  0,  0],
       [50, 17, 17, 11,  4,  1,  0,  0],
       [39,  0, 26, 19, 14,  1,  1,  0],
       [42, 21, 16, 10,  8,  3,  0,  0],
       [34, 17, 20, 20,  5,  2,  1,  0],
       [39, 13, 17, 19, 10,  1,  1,  0],
       [38, 15, 23, 15,  8,  0,  1,  0],
       [42, 18, 25,  9,  5,  1,  0,  0],
       [36, 14, 21, 14, 11,  2,  1,  0],
       [38, 15, 31,  8,  6,  1,  1,  0],
       [36, 16, 24, 12,  9,  1,  1,  0],
       [34, 17, 23, 11, 13,  0,  1,  0]], dtype=int64)

In [143]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33)

In [148]:
X_train

array([[42, 18, 25,  9,  5,  1,  0,  0],
       [34, 17, 23, 11, 13,  0,  1,  0],
       [36, 16, 24, 12,  9,  1,  1,  0],
       [45, 11, 17, 17,  8,  1,  0,  0],
       [55, 27,  3,  7,  5,  2,  1,  0],
       [34, 17, 20, 20,  5,  2,  1,  0],
       [42, 21, 16, 10,  8,  3,  0,  0],
       [47, 23, 18,  6,  4,  1,  0,  0],
       [50, 17, 17,  8,  6,  1,  0,  0],
       [50, 17, 17, 11,  4,  1,  0,  0],
       [55, 28,  3,  7,  5,  2,  0,  0],
       [47, 24, 12,  6,  9,  1,  0,  0],
       [47, 26, 10, 10,  4,  1,  0,  0]], dtype=int64)

In [149]:
from sklearn.svm import SVC
C=[1,10,100]
kernel=['linear','rbf','sigmoid','poly']
for i in C:
    for j in kernel:
        model = SVC(C=i,kernel=j, gamma='auto').fit(X_train, y_train)
        print(i,j,model.score(X_test, y_test))

1 linear 1.0
1 rbf 0.285714285714
1 sigmoid 0.285714285714
1 poly 1.0
10 linear 1.0
10 rbf 0.285714285714
10 sigmoid 0.285714285714
10 poly 1.0
100 linear 1.0
100 rbf 0.285714285714
100 sigmoid 0.285714285714
100 poly 1.0

In [150]:
model_best = SVC(kernel='linear').fit(X_train, y_train)

#Let's store the prediction of our model and later compare it with the y_test
y_pred=model_best.predict(X_test)

In [151]:
from sklearn.svm import SVC
svc_modell=SVC().fit(x,y)
svc_modell.score(x,y)

1.0

In [152]:
svc_modell.predict([[34, 17, 23, 11, 13,  0,  1,  0]])

array([1], dtype=int64)